Update employee_validator.yaml

diff --git a/.github/workflows/employee_validator.yaml b/.github/workflows/employee_validator.yaml
--- a/.github/workflows/employee_validator.yaml
+++ b/.github/workflows/employee_validator.yaml
@@ -25,11 +25,13 @@ jobs:
           employee: ${{ github.event.inputs.emp_name }}
 
       - name: Print result
-        run: echo "${{ steps.check_employee.outputs.result }}"
-        if: steps.check_employee.outputs.result == 'Found'
+        run: |
+         result="${{ steps.check_employee.outputs.result }}"
+         echo "$result"
+          if [ "$result" == 'Found' ]; then
+            echo "Success! Continue with additional actions."
+          else
+            echo "Error: Result is not 'Found'. Exiting."
+            exit 1
+          fi
 
-  # Mark the workflow as failed if the result is not 'Found'
-  
-      - name: Fail workflow
-        if: failure()
-        run: exit 1
